---
title: "Employment and Underemployment in the Labour Force Survey"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Employment and Underemployment in the Labour Force Survey}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 7, fig.height = 5.5,
  comment = "#>"
)
```

```{r setup, warning=FALSE,message=FALSE}
library(lfsclean)
library(tidyr)
library(tidyverse)
library(ggthemes)
library(zoo)
```

## Introduction

## Data cleaning

The code below makes use of `lfsclean` to clean the raw survey data and produce a dataset that can be used for analysis of hours and employment. 

```{r reading, eval = FALSE}
#### read in and clean raw data using the package

####################
## input arguments

root  <- "C:/"
file  <- "" # path to the folder where the tab files are
year  <- 1993:2023
ages  <- 16:64
keep_vars <- NULL
complete_vars <- NULL

##############################
### LFS data 1993 - 2022

lfs_data <- lfsclean(root = root,
                     file = file,
                     year = year,
                     ages = ages,
                     keep_vars = keep_vars,
                     complete_vars = complete_vars)
```


The code below can be used to recreate the unemployment / underemployment rate calculations

```{r cleaning, eval = FALSE}
lfs_data_clean <- lfs_data %>%
  filter(!is.na(l_lmstatus_3cat)) %>%
  filter(!is.na(pwt)) %>%
  filter(l_lmstatus_3cat %in% c("employed","unemployed")) %>%
  select(month,quarter,year,pwt,l_lmstatus_3cat,eh_uhours,eh_undhrs,eh_ovhrs) %>%
  mutate(eh_ovhrs = ifelse(is.na(eh_ovhrs),0,eh_ovhrs),
         eh_undhrs = ifelse(is.na(eh_undhrs),0,eh_undhrs)) %>%
  mutate(mean_hours = weighted.mean(eh_uhours, w = pwt, na.rm = TRUE),
         unemployed = ifelse(l_lmstatus_3cat == "employed",0,1),
         employed = ifelse(l_lmstatus_3cat == "unemployed",0,1)) %>%
  group_by(year,quarter) %>%
  summarise(unemp_rate     = sum(pwt*unemployed)/(sum(pwt*unemployed) + sum(pwt*employed)),
            unemp_rate_hrs = sum(pwt*unemployed*mean_hours)/(sum(pwt*unemployed*mean_hours) + sum(pwt*employed*mean_hours)),
            underemp_rate  = (sum(pwt*unemployed*mean_hours) + sum(pwt*eh_undhrs) - sum(pwt*eh_ovhrs))/(sum(pwt*unemployed*mean_hours) + sum(pwt*employed*mean_hours)),
            population = sum(pwt)) %>%
  ungroup() %>%
  mutate(time = zoo::as.yearqtr(paste(year,quarter), "%Y %q"))
```

## Unemployment and Underemployment

```{r underemployment, echo = FALSE, warning = FALSE}
path <- here::here("vignettes/LFS_underemployment")

lfs_data_clean <- readRDS(paste0(path,"/underemployment_data.rds"))

ggplot(lfs_data_clean) +
  geom_line(aes(x = time, y = unemp_rate),    color = "#f4a261", linewidth = 1.2) +
  geom_line(aes(x = time, y = underemp_rate), color = "#8d0801", linewidth = 1.2) +
  theme_classic() +
  scale_y_continuous(breaks = seq(0,0.15,0.005), labels = scales::percent) +
  labs(x = "year-quarter",
       y = "Unemployment Rate (%)")
```



```{r difference, echo = FALSE, warning = FALSE}
path <- here::here("vignettes/LFS_underemployment")

lfs_data_clean <- readRDS(paste0(path,"/underemployment_data.rds")) %>%
  mutate(diff = hours_diff/mean_hours) %>%
  filter(year >= 2001)

ggplot(lfs_data_clean[!is.na(diff),]) +
  geom_line(aes(x = time, y = diff/1000),    color = "#8d0801", linewidth = 1.2) +
  geom_hline(yintercept = 0) +
  theme_classic() +
  scale_y_continuous(breaks = seq(-1000,1000,100)) +
  labs(x = "year-quarter",
       y = "Net under-employment of the employed \nas number of FTE workers (000s)")
```

